-- vim.g.XkbSwitchEnabled = 1;
-- vim.g.XkbSwitchAssistNKeymap = 1;    -- for commands r and f
-- vim.g.XkbSwitchAssistSKeymap = 1; -- for search lines
-- vim.g.XkbSwitchLib = '/usr/lib64/g3kb-switch/libg3kbswitch.so';
