require('plugins.packer')
require('plugins.lualine')
require('plugins.onedark')
require('plugins.xkbswitch')
require('plugins.telescope')
require('plugins.treesitter')
require('plugins.hop')
require('plugins.nvim_comment')
